# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-25 10:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('direccion', models.TextField()),
                ('telefono', models.CharField(max_length=12)),
                ('responsable', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254)),
                ('fecha_alta', models.DateTimeField(auto_now_add=True)),
                ('fecha_ultima_mod', models.DateField(auto_now=True)),
                ('comentario', models.TextField()),
                ('activo', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Locacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('comentario', models.TextField()),
                ('activo', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=70)),
                ('documento', models.CharField(max_length=10)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='personas/archivo/%Y/%m/%d')),
                ('fecha_alta', models.DateField(auto_now_add=True)),
                ('fecha_ultima_mod', models.DateField(auto_now=True)),
                ('activo', models.BooleanField()),
                ('empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cdap.Empresa')),
            ],
        ),
        migrations.AddField(
            model_name='empresa',
            name='locacion',
            field=models.ManyToManyField(to='cdap.Locacion'),
        ),
    ]
